### ISSUE TITLE
"npm install" doesn't work out of the box

### ISSUE THREAD

**Issue by tsondergaard** [rhappdev/nodejs-template#1]
I'm fairly new to npm, but the problem appears to be caused by .npmrc that references a specific registry:

`registry = "http://nexus3-misanche-nexus.apps.na39.openshift.opentlc.com/repository/npm_group"`

That registry fails with "503 Service Unavailable" for me.

**Comment by misanche** [comment]
@tsondergaard sorry, I didn't see the issue. It's not an issue itself. I added the .npmrc file with an example for setting a private npm registry. if you want to use npm repository, just remove this file.

**Comment by misanche** [comment]
Updated Readme.md with common issues.

https://github.com/rhappdev/nodejs-template/blob/master/Readme.md#npm-install-fails

**Comment by sonal994** [comment]
Any update on this?

**Comment by misanche** [comment]
@sonal994 read https://github.com/rhappdev/nodejs-template/blob/master/Readme.md#npm-install-fails renové the .npmrc file and try again. This happens because we use internal npm repository.

**Comment by sonal994** [comment]
@misanche After deleting that file,  It is showing below error on npm start :npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodets-sample@1.0.0 start: `DEBUG=fes:* node dist/index.js`

**Comment by misanche** [comment]
Hi @sonal994 did you run first:
npm run build:live or npm run build:dev first?

The reason is because we develop in typescript and then we transpile it to js. Once you run the command, the dish folder will be available

**Comment by sonal994** [comment]
Thanks @misanche .

**Comment by misanche** [comment]
np @sonal994 glad to help
