### ISSUE TITLE
Unable to complete npm install

### ISSUE THREAD

**Issue by deewhyweb** [rhappdev/nodejs-template#2]
Seeing the following issue with:  http://nexus3-misanche-nexus.apps.na39.openshift.opentlc.com/repository/npm_group/arr-diff/-/arr-diff-2.0.0.tgz

Is it possible to get this dependency moved to a public repo?

npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to http://nexus3-misanche-nexus.apps.na39.openshift.opentlc.com/repository/npm_group/arr-diff/-/arr-diff-2.0.0.tgz failed, reason: connect ETIMEDOUT 54.203.116.143:80
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by primashah** [comment]
@deewhyweb The dependancy was just added as an example. Refer issue #1 for details.

**Comment by misanche** [comment]
@deewhyweb remove the .npmrc file as explained at: https://github.com/rhappdev/nodejs-template/blob/master/Readme.md#npm-install-fails

can I close the issue?
