### ISSUE TITLE
unable to find dist folder

### ISSUE THREAD

**Issue by ElectroP** [rhappdev/nodejs-template#3]
Not able to find dist folder as mentioned in the folder structure after downloading this project

**Comment by misanche** [comment]
HI @ElectroP have you tried first to run:

`npm run build:live`

or 

`npm run build:dev`
?

Please tell me if that works and I close the issue

**Comment by ElectroP** [comment]
That worked!!....but i want see dist folder structure created while build..how to check that?

**Comment by misanche** [comment]
@ElectroP the strucuture is just the same as the one that appears in /src, the difference is that src uses Typescript and dist is the code transpilation

**Comment by ElectroP** [comment]
thanks for the clarification.
