### ISSUE TITLE
swagger spec endpoint appears to not be working

### ISSUE THREAD

**Issue by gcohler** [rhappdev/nodejs-template#5]
The swagger Spec Endpoint : http://localhost:8001/api-docs noted in the readme does not appear to work.  Do you see the same thing?  The swagger-ui Endpoint : http://localhost:8001/docs works great.  (running on the OASv3 branch)

**Comment by fbele** [comment]
> The swagger Spec Endpoint : http://localhost:8001/api-docs noted in the readme does not appear to work. Do you see the same thing? The swagger-ui Endpoint : http://localhost:8001/docs works great. (running on the OASv3 branch)

I have the same issue. Did you find any solution?

**Comment by gcohler** [comment]
@fbele I don't think the capability exists anymore.  I think the readme is wrong.  It appears to me that it serves it up as a website only -- not as a yaml doc.  It wasn't that important to me -- so not going to propose any change.
